version: "3.8"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: doatech
      MYSQL_DATABASE: doatech 
      MYSQL_USER: doatech
      MYSQL_PASSWORD: doatech

  app:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: doatech
      TYPEORM_PASSWORD: doatech
      TYPEORM_DATABASE: doatech
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 'false'
      TYPEORM_LOGGING: 'false'
      TYPEORM_ENTITIES: dist/models/*.js
      TYPEORM_ENTITIES_DIR: src/models/
      TYPEORM_MIGRATIONS: dist/models/migrations/*.js
      TYPEORM_MIGRATIONS_DIR: src/models/migrations/
      JWT_SECRET: secret
      ONG_NAME: doatech
      ONG_EMAIL: doatech
      ONG_PASSWORD: doatech
